#!/usr/bin/env python3

import itertools
import os
import sys

import taas

directory = "/var/log"
os.chdir(directory)
file = os.path.realpath(sys.argv[1])

## as with chroot or docker volume shenanigans, this doesn't allow symlinks that point outside of /var/log
assert file.startswith(os.path.realpath(directory))

line_count = int(sys.argv[2])
needle = sys.argv[3].encode()
for l in itertools.islice(filter(lambda line: line.find(needle) != -1, taas.reverse_lines(file)), line_count):
    sys.stdout.buffer.write(l)

# import resource
# print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
